### PR TITLE
Fix build system

### PR DESCRIPTION
**Pull request by r-barnes**

### CODE REVIEW

**Comment by r-barnes** [comment]
Note that `kilosim` should be a submodule of the project. This ensures that the user isn't surprised by API changes to kilosim elsewhere on their machine unexpectedly propagating into an older project. This also saves the trouble of the user having to install kilosim system-wide.

Source files should be listed explicitly in `CMakeLists.txt`. This way if files are added or subtracted the build system can automatically account for it.

Compilation for production should be done with the `-DCMAKE_BUILD_TYPE=Release` flag.

**Comment by r-barnes** [comment]
Ideally, the header files should be in a separate directory, e.g. `api/kilosim_demo/header.hpp`. This way the project is already set up to itself be included in other projects, though I haven't made this change.

**Comment by jtebert** [comment]
Is `submodules/kilosim` supposed to be included as a folder in this repository?

**Comment by r-barnes** [comment]
No. `kilosim` is included as a submodule. So git keeps track of which commit hash this repo uses for the library. During cloning the `submodules/kilosim` directory is populated. The README explains this somewhat.

**Comment by r-barnes** [comment]
I'll let you merge when you're ready.

**Comment by jtebert** [comment]
Sorry, I think I'm still a little confused about the submodules workflow. The version you committed did have the submodules directory in it. When I've deleted it, I can't seem to get it to work.

I re-cloned the project with `git clone --recurse-submodules https://github.com/jtebert/kilosim-demo` and switched to this branch. Is this supposed to handle the initialization for the submodule/kilosim? It doesn't seem to do anything differently, so when I then try to run the `cmake`, it complains that the `submodule/kilosim` directory doesn't exist.

**Comment by r-barnes** [comment]
You're cloning master by default, so it doesn't get the submodule. After
switching to the appropriate branch use the other line in the README.

**Pull request merged**
